#!/usr/bin/env bats

# scripts/check-session-url.sh の単体テスト．
#
# 仕様:
#   入力（環境変数）
#     GH_TOKEN  - GitHub token（必須）
#     REPO      - owner/repo（必須）
#     PR_NUMBER - PR 番号（必須）
#   動作
#     - PR のタイトル・本文と全コミットメッセージを gh api で取得し，
#       Claude Code のセッション URL（claude.ai/code/session_… / cse_…）と
#       Claude-Session: trailer を大文字小文字を区別せず検索する．
#     - 検出なしは exit 0 と成功メッセージ．
#     - 検出ありは行ごとの ::error:: と件数の ::error:: を出し exit 1．
#     - gh api の失敗は ::error:: を出し exit 2（fail-closed）．
#     - 必須 env が欠けている場合は非 0 終了．
#
# テスト戦略:
#   - 実 API を叩かないため，PATH の前段に fake gh を仕込む．
#     script が使う 2 種の呼び出しを endpoint（/commits の有無）で見分け，
#     jq 適用後の行を FAKE_GH_PR_LINES / FAKE_GH_COMMIT_LINES から返す．
#     終了コードは FAKE_GH_PR_EXIT / FAKE_GH_COMMITS_EXIT で切り替える．

setup() {
  REPO_ROOT="$(cd "${BATS_TEST_DIRNAME}/../.." && pwd)"
  SCRIPT="${REPO_ROOT}/scripts/check-session-url.sh"
  FAKE_BIN="${BATS_TEST_TMPDIR}/bin"
  mkdir -p "${FAKE_BIN}"
  cat >"${FAKE_BIN}/gh" <<'FAKE'
#!/usr/bin/env bash
# テスト用 fake gh．/commits を含む endpoint ならコミット行，それ以外は PR 行を返す．
is_commits=0
for arg in "$@"; do
  case "${arg}" in
    */commits) is_commits=1 ;;
  esac
done
if [ "${is_commits}" -eq 1 ]; then
  printf '%s' "${FAKE_GH_COMMIT_LINES:-}"
  exit "${FAKE_GH_COMMITS_EXIT:-0}"
fi
printf '%s' "${FAKE_GH_PR_LINES:-}"
exit "${FAKE_GH_PR_EXIT:-0}"
FAKE
  chmod +x "${FAKE_BIN}/gh"
  PATH="${FAKE_BIN}:${PATH}"
  export PATH
  export GH_TOKEN="fake-token"
  export REPO="acme/repo"
  export PR_NUMBER="42"
  # 既定は clean な PR．個別テストで上書きする．
  export FAKE_GH_PR_LINES=$'pull-request\tfeat: add thing\npull-request\t\npull-request\tThis PR adds a thing.'
  export FAKE_GH_COMMIT_LINES=$'abc123\tfeat: add thing\nabc123\t\nabc123\tCo-Authored-By: Claude <noreply@anthropic.com>'
  # テスト用のセッション URL．実在のセッションではない．
  URL='https://claude.ai/code/session_01TESTSESSIONID'
}

teardown() {
  unset FAKE_GH_PR_LINES FAKE_GH_COMMIT_LINES FAKE_GH_PR_EXIT FAKE_GH_COMMITS_EXIT
  unset GH_TOKEN REPO PR_NUMBER
}

@test "clean な PR は exit 0 で成功メッセージを出す" {
  run bash "${SCRIPT}"

  [ "${status}" -eq 0 ]
  [[ "${output}" == *"No Claude session URL found in PR #42"* ]]
}

@test "trailer 形式のコミットは exit 1 で SHA と行を報告する" {
  export FAKE_GH_COMMIT_LINES=$'abc123\tfix: x\nabc123\t\nabc123\tClaude-Session: '"${URL}"

  run bash "${SCRIPT}"

  [ "${status}" -eq 1 ]
  [[ "${output}" == *"::error::Claude session URL found in abc123: Claude-Session: ${URL}"* ]]
  [[ "${output}" == *"1 line(s) contain a Claude session URL"* ]]
}

@test "素の URL 形式のコミットも exit 1 で報告する" {
  export FAKE_GH_COMMIT_LINES=$'def456\tfix: y\ndef456\t\ndef456\t'"${URL}"

  run bash "${SCRIPT}"

  [ "${status}" -eq 1 ]
  [[ "${output}" == *"found in def456: ${URL}"* ]]
}

@test "PR 本文の URL は pull-request として報告する" {
  export FAKE_GH_PR_LINES=$'pull-request\tfeat: z\npull-request\t\npull-request\tGenerated by '"${URL}"

  run bash "${SCRIPT}"

  [ "${status}" -eq 1 ]
  [[ "${output}" == *"found in pull-request: Generated by ${URL}"* ]]
}

@test "大文字小文字を区別せずに検出する" {
  export FAKE_GH_COMMIT_LINES=$'abc123\tHTTPS://CLAUDE.AI/CODE/SESSION_01TESTSESSIONID'

  run bash "${SCRIPT}"

  [ "${status}" -eq 1 ]
}

@test "cse_ 形式の ID も検出する" {
  export FAKE_GH_COMMIT_LINES=$'abc123\thttps://claude.ai/code/cse_01TESTSESSIONID'

  run bash "${SCRIPT}"

  [ "${status}" -eq 1 ]
}

@test "複数行の検出は件数をまとめて報告する" {
  export FAKE_GH_PR_LINES=$'pull-request\t'"${URL}"
  export FAKE_GH_COMMIT_LINES=$'abc123\tClaude-Session: '"${URL}"$'\ndef456\t'"${URL}"

  run bash "${SCRIPT}"

  [ "${status}" -eq 1 ]
  [[ "${output}" == *"3 line(s) contain a Claude session URL"* ]]
}

@test "セッション ID を伴わない claude.ai/code は検出しない（誤検知回帰防止）" {
  export FAKE_GH_COMMIT_LINES=$'abc123\tdocs: link https://claude.ai/code in README'

  run bash "${SCRIPT}"

  [ "${status}" -eq 0 ]
}

@test "PR の取得失敗は exit 2（fail-closed）" {
  export FAKE_GH_PR_EXIT=1

  run bash "${SCRIPT}"

  [ "${status}" -eq 2 ]
  [[ "${output}" == *"::error::Failed to fetch pull request #42"* ]]
}

@test "コミットの取得失敗は exit 2（fail-closed）" {
  export FAKE_GH_COMMITS_EXIT=1

  run bash "${SCRIPT}"

  [ "${status}" -eq 2 ]
  [[ "${output}" == *"::error::Failed to fetch commits of pull request #42"* ]]
}

@test "GH_TOKEN 未設定で非 0 終了" {
  unset GH_TOKEN

  run bash "${SCRIPT}"

  [ "${status}" -ne 0 ]
}

@test "REPO 未設定で非 0 終了" {
  unset REPO

  run bash "${SCRIPT}"

  [ "${status}" -ne 0 ]
}

@test "PR_NUMBER 未設定で非 0 終了" {
  unset PR_NUMBER

  run bash "${SCRIPT}"

  [ "${status}" -ne 0 ]
}
